[2024-12-09T20:29:29.820+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T20:29:29.834+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data_pipeline_mongodb.load_data scheduled__2024-12-06T00:00:00+00:00 [queued]>
[2024-12-09T20:29:29.840+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data_pipeline_mongodb.load_data scheduled__2024-12-06T00:00:00+00:00 [queued]>
[2024-12-09T20:29:29.840+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-09T20:29:29.852+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2024-12-06 00:00:00+00:00
[2024-12-09T20:29:29.859+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=412) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-09T20:29:29.862+0000] {standard_task_runner.py:72} INFO - Started process 416 to run task
[2024-12-09T20:29:29.862+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_data_pipeline_mongodb', 'load_data', 'scheduled__2024-12-06T00:00:00+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/etl_data_pipeline_mongodb.py', '--cfg-path', '/tmp/tmpdccnv_x1']
[2024-12-09T20:29:29.863+0000] {standard_task_runner.py:105} INFO - Job 265: Subtask load_data
[2024-12-09T20:29:30.168+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_data_pipeline_mongodb.load_data scheduled__2024-12-06T00:00:00+00:00 [running]> on host 8553af9ff67b
[2024-12-09T20:29:30.249+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data_pipeline_mongodb' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-06T00:00:00+00:00'
[2024-12-09T20:29:30.251+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-09T20:29:30.251+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-09T20:29:30.252+0000] {logging_mixin.py:190} INFO - Current task name:load_data state:running start_date:2024-12-09 20:29:29.834532+00:00
[2024-12-09T20:29:30.252+0000] {logging_mixin.py:190} INFO - Dag name:etl_data_pipeline_mongodb and current dag run status:running
[2024-12-09T20:29:30.253+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T20:29:30.299+0000] {logging_mixin.py:190} INFO - Données chargées dans MongoDB, collection 'cleaned_data'
[2024-12-09T20:29:30.300+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-09T20:29:30.310+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T20:29:30.311+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_data_pipeline_mongodb, task_id=load_data, run_id=scheduled__2024-12-06T00:00:00+00:00, execution_date=20241206T000000, start_date=20241209T202929, end_date=20241209T202930
[2024-12-09T20:29:30.322+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-09T20:29:30.322+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-09T20:29:30.323+0000] {logging_mixin.py:190} INFO - Dag name:etl_data_pipeline_mongodb queued_at:2024-12-07 20:07:06.963892+00:00
[2024-12-09T20:29:30.323+0000] {logging_mixin.py:190} INFO - Task hostname:8553af9ff67b operator:PythonOperator
[2024-12-09T20:29:30.359+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-09T20:29:30.545+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-09T20:29:30.547+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
